#:import Toolbar kivymd.toolbar.Toolbar

BoxLayout:
    orientation: 'vertical'
    Toolbar:
        id: toolbar
        title: 'Welcome'
        background_color: app.theme_cls.primary_dark
        left_action_items: [['menu', lambda x: app.nav_drawer.toggle()]]
    ScreenManagement:
        id: manager
        background_color: app.theme_cls.primary_dark
        size_hint: 1, 0.5
        AboutScreen:
            id: about
        SettingsScreen:
            id: settings